---
remotes:
  primary: git@github.com:destructuring/alpha_omega
  secondary: git@bitbucket.org:destructuring/alpha_omega
  rb: https://github.com/destructuring/rb-helper
  bump: https://github.com/destructuring/mixin-bump
