---
remotes:
  primary: git@github.com:destructuring/alpha_omega
  secondary: git@bitbucket.org:destructuring/alpha_omega
  sh: https://github.com/destructuring/jason
  bump: https://github.com/destructuring/mixin-bump
