--- 
repository: https://github.com/destructuring/alpha_omega
application: alpha_omega

ruby_loader: rvm-exec
app_ruby: ree

branches: [ master ]
branch_regex: /

chef_path: /data/zendesk_chef

notify:
  nothing:
